# Generated by Django 5.0.6 on 2024-06-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bevölkerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=50)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=50)),
                ('total_population', models.IntegerField(null=True)),
                ('male_population', models.IntegerField(null=True)),
                ('female_population', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hochschulen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzname', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(max_length=50)),
                ('trägerschaft', models.CharField(max_length=50)),
                ('bundesland', models.CharField(max_length=50)),
                ('anz_studis', models.IntegerField(null=True)),
                ('gründungsjahr', models.IntegerField(null=True)),
                ('promotionsrecht', models.BooleanField()),
                ('habilitationsrecht', models.BooleanField()),
                ('straße', models.CharField(max_length=200)),
                ('postleitzahl', models.IntegerField(null=True)),
                ('ort', models.CharField(max_length=50)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('homepage', models.URLField(blank=True)),
            ],
        ),
    ]
