# Generated by Django 5.0.6 on 2024-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bevölkerung_dg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bevölkerung',
            name='name',
        ),
    ]
