# Generated by Django 5.0.6 on 2024-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bevölkerung_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bevölkerung',
            name='ort',
            field=models.CharField(max_length=250),
        ),
    ]
